version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Adjust the port mapping as needed
    volumes:
      - .:/app  # Mount the current directory to /app in the container
